apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
    name: http
  selector:
    app: nginx-ingress